# Generated by Django 3.1.5 on 2021-01-27 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(default='')),
                ('link', models.URLField()),
                ('image_url', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(unique=True)),
                ('description', models.TextField(default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('category', models.TextField(default='')),
                ('publish_date', models.DateTimeField(db_index=True)),
                ('author', models.TextField(default='')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='rss.channel')),
            ],
            options={
                'ordering': ('-publish_date',),
            },
        ),
    ]
