# Generated by Django 3.1.5 on 2021-01-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_auto_20210127_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='entry',
            name='link',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
