# Generated by Django 3.1.5 on 2021-01-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_auto_20210130_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
