# Generated by Django 3.1.5 on 2021-01-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_auto_20210126_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
