# Generated by Django 3.1.5 on 2021-01-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0004_channel_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='image_url',
        ),
    ]
