# Generated by Django 3.1.5 on 2021-01-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_auto_20210125_2356'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marked_entries',
            field=models.ManyToManyField(related_name='_user_marked_entries_+', to='rss.Entry'),
        ),
        migrations.AddField(
            model_name='user',
            name='read_entries',
            field=models.ManyToManyField(related_name='_user_read_entries_+', to='rss.Entry'),
        ),
    ]
