# Generated by Django 3.1.5 on 2021-01-27 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210125_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='marked_entries',
        ),
        migrations.RemoveField(
            model_name='user',
            name='read_entries',
        ),
    ]
